library(shiny)
library(shinyFiles)
library(bslib)

ui <- fluidPage(
  theme = bs_theme(bootswatch = "lux", primary = "#680dad", secondary = "#9867ea"),
  
  tags$head(
    tags$style(
      HTML("
        .container {
          margin: 200px;
        }
        .main-panel img {
          width: 100%;
          height: auto;
        }
      ")
    )
  ),
  
  div(class = "mt-4",  # Margin top class added to this div
      titlePanel("Generative AI Quarto Theme Generator")
  ),
  
  sidebarLayout(
    sidebarPanel(
      textInput("user_input", "Enter a phrase for the theme:", value = "Abstract purple minimal"),
      textInput("api_key", "Enter your OpenAI API key"),
      helpText("Use the button below to select a folder where you'd like to save the files to."),
      br(),
      br(),
      shinyDirButton("folder_location", "Select Folder", "Please select a folder"),
      br(),
      br(),
      helpText("Click the button below to generate the necessary files (warning: clicking this will cost money!)"),
      br(),
      br(),
      actionButton("generate_button", "Generate my theme")
    ),
    
    mainPanel(class = "main-panel",
      textOutput("status"),
      tags$p("This app will take your phrase, and pass it to ChatGPT to generate a Quarto revealjs theme. 10 images will be generated by the image generation endpoint as part of this process. Please see the ",
             tags$a(href = "https://openai.com/pricing", target = "_blank", "OpenAI API pricing page"),
             " to determine the cost of using this app (approximately $0.40 as of June 2024)."),
      tags$img(src = "demo.png", alt = "Demo Image", style = "margin-top: 20px;")
    )
  )
)
