library(shiny)
library(shinyFiles)
library(bslib)

ui <- fluidPage(
  theme = bs_theme(bootswatch = "lux", primary = "#680dad", secondary = "#9867ea"),
  
  tags$head(
    tags$link(rel = "icon", type = "image/png", href = "favicon.png"),
    tags$style(
      HTML("
        .container {
          margin: 200px;
        }
        .main-panel img {
          width: 100%;
          height: auto;
        }
        .purple-background {
          background-color: #E6E6FA;
          padding: 10px;
          border-radius: 5px;
        }
      ")
    )
  ),
  
  div(class = "mt-4",  # Margin top class added to this div
      titlePanel("Generative AI Quarto Theme Generator")
  ),
  
  sidebarLayout(
    sidebarPanel(
      textInput("user_input", "Enter a phrase for the theme:", value = "Abstract purple minimal"),
      textInput("api_key", "Enter your OpenAI API key"),
      checkboxInput("images_checkbox", "Generate images in addition to CSS?", value = FALSE),
      helpText('Click the button below to generate the necessary files (warning: clicking this will cost more money and take several minutes longer if the "generate images" checkbox is checked!)'),
      br(),
      br(),
      actionButton("generate_button", "Generate my theme"),
      br(),
      br(),
      helpText('Once you see a message highlighted in purple saying "Theme generated successfully!", you may download all the generated files.'),
      br(),
      br(),
      downloadButton("downloadData", "Download All Files"),
      br(),
      br(),
      tags$p("© 2024 ", tags$a(href = "https://www.melissavanbussel.com", target = "_blank", "Melissa Van Bussel"))
    ),
    
    mainPanel(class = "main-panel",
      br(),
      uiOutput("status"),
      br(),
      br(),
      tags$p('This app will take your phrase, and pass it to ChatGPT to choose fonts and colours that the app will then use to generate a Quarto revealjs theme. If the "generate images" checkbox is checked off, 10 images will be generated by the image generation endpoint as part of this process. Please see the ',
             tags$a(href = "https://openai.com/pricing", target = "_blank", "OpenAI API pricing page"),
             'to determine the cost of using this feature (approximately $0.40 as of June 2024). If the "generate images" checkbox is not checked, the cost of running the app will be less than a penny based on June 2024 API pricing.'),
      tags$img(src = "demo.png", alt = "Demo Image", style = "margin-top: 20px;")
    )
  )
)
